spring:
  application:
    name: "grocery-tracker-api"

  data:
    mongodb:
      uri: "mongodb+srv://arjunkarnae:ylTkvDzykNpfYZdZ@cluster0.6yymcol.mongodb.net/grocery-tracker-db?retryWrites=true&w=majority&appName=Cluster0"

jwt:
  security:
    key: "ae17a0b4d4253971b4c52ab84d0087e5e5a8735359111adc25836e4ecbd663e8"